### ISSUE TITLE
umbrella issue - `scikit-base` based rearchitecture for `skpro` v2

### ISSUE THREAD

**Issue by fkiraly** [sktime/skpro#10]
- [ ] 1st part: rearchitecting on scikit-base https://github.com/sktime/skpro/pull/9 - 
  this unlocks creating new estimators, distributions, and moving legacy estimators to scikit-base compatible interface
- [ ] 2nd part to cover probabilistic metrics and example notebooks
  this unlocks more metrics and moving legacy metrics

Moving individual estimators from legacy to `scikit-base` interface

- [ ] complete missing features in residual two-step
- [ ] bagging estimator
- [ ] density estimator naive baseline (should include kernel and empirical
- [ ] composite parametric
- [ ] bounding wrapper
- [ ] grid and random tuning (requires metrics)

Moving distirbutions from legacy to `scikit-base` interface

- [ ] Laplace
- [ ] Cauchy
- [ ] t
- [ ] empirical
- [ ] mixture (compositor)

Moving metrics from legacy to `scikit-base` interface - can be reused from `sktime`

- [ ] CRPS
- [ ] log-loss
- [ ] capped log-loss
- [ ] squared loss
